import Link from "next/link";
import { ArrowRight, FileText, History, SlidersHorizontal } from "lucide-react";

import { ArchiveCompanyButton, CompanyMetadataForm, FileActions, FileUploadForm, OpenAnalysisLink } from "@/features/workspace/components/workspace-forms";
import { formatWorkspaceDate } from "@/features/workspace/components/workspace-shell";

type CompanyWorkspace = Awaited<ReturnType<typeof import("@/server/accounts/workspace-data").loadCompanyWorkspace>>;
type HistoryWorkspace = Awaited<ReturnType<typeof import("@/server/accounts/workspace-data").loadAnalysisHistory>>;
type FilesWorkspace = Awaited<ReturnType<typeof import("@/server/accounts/workspace-data").loadWorkspaceFiles>>;
type ScenariosWorkspace = Awaited<ReturnType<typeof import("@/server/accounts/workspace-data").loadWorkspaceScenarios>>;

export function CompaniesCollection({ data }: { data: Pick<Awaited<ReturnType<typeof import("@/server/accounts/workspace-data").loadWorkspaceOverview>>, "companies"> }) {
  return <section className="open-section"><div className="mb-6"><p className="premium-kicker">Companies</p><h1 className="mt-2 text-h2 font-semibold text-white">Companies that anchor your analysis</h1><p className="mt-2 max-w-2xl text-small leading-6 text-neutral-400">Archiving preserves the immutable financial and analysis history already associated with a company.</p></div>{data.companies.items.length ? <div className="grid gap-2 border-y border-border">{data.companies.items.map((company) => <article className="grid gap-3 py-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center" key={company.id}><div><p className="text-h4 font-semibold text-white">{company.name}</p><p className="mt-1 text-small text-neutral-400">{company.industry} · {company.currency} · Created {formatWorkspaceDate(company.createdAt)}</p></div><Link className="inline-flex items-center gap-2 text-small font-semibold text-blue-200 hover:text-white" href={`/workspace/companies/${company.id}`}>Open company <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link></article>)}</div> : <p className="premium-panel rounded-lg p-6 text-small text-neutral-400">No companies yet. Create your first company from the workspace overview or save a completed financial input.</p>}</section>;
}

export function CompanyWorkspaceView({ data }: { data: CompanyWorkspace }) {
  const { company } = data;
  return <div className="grid gap-8"><section className="premium-ambient grid gap-5 border-b border-border pb-8 lg:grid-cols-[minmax(0,1fr)_auto]"><div><p className="premium-kicker">Company workspace</p><h1 className="mt-2 text-h1 font-semibold tracking-tight text-white">{company.name}</h1><p className="mt-2 text-body text-neutral-300">{company.industry} · {company.currency}</p></div><Link className="inline-flex items-center gap-2 self-start text-small font-semibold text-blue-200" href="/input">Create new financial data <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link></section><section className="premium-panel rounded-lg p-5"><h2 className="text-h4 font-semibold text-white">Company details</h2><div className="mt-5"><CompanyMetadataForm company={company} /></div><div className="mt-6 border-t border-border pt-5"><ArchiveCompanyButton companyId={company.id} /></div></section><section className="grid gap-5 xl:grid-cols-3"><CompanySection icon={History} items={data.analyses.items} label="Analyses" render={(analysis) => <><p className="font-semibold text-white">{analysis.status}</p><p className="text-caption text-neutral-400">{formatWorkspaceDate(analysis.createdAt)}</p><OpenAnalysisLink runId={analysis.id} /></>} /><CompanySection icon={SlidersHorizontal} items={data.scenarios.items} label="Saved scenarios" render={(scenario) => <><p className="font-semibold text-white">{scenario.name}</p><p className="text-caption text-neutral-400">{formatWorkspaceDate(scenario.createdAt)}</p><Link className="text-caption font-semibold text-blue-200" href={`/workspace/scenarios/${scenario.id}`}>Open scenario</Link></>} /><CompanySection icon={FileText} items={data.files.items} label="Private files" render={(file) => <><p className="truncate font-semibold text-white">{file.originalFilename}</p><p className="text-caption text-neutral-400">{formatWorkspaceDate(file.createdAt)}</p></>} /></section><section className="open-section"><p className="premium-kicker">Financial data</p><h2 className="mt-2 text-h3 font-semibold text-white">Immutable datasets</h2>{data.datasets.items.length ? <div className="mt-5 grid divide-y divide-border border-y border-border">{data.datasets.items.map(({ dataset }) => <div className="flex items-center justify-between gap-4 py-4" key={dataset.id}><span><span className="block text-small font-semibold text-white">{dataset.name}</span><span className="text-caption text-neutral-400">Created {formatWorkspaceDate(dataset.createdAt)}</span></span><span className="text-caption text-neutral-400">Version history retained</span></div>)}</div> : <p className="mt-4 text-small text-neutral-400">No dataset is stored for this company yet.</p>}</section></div>;
}

function CompanySection<T extends { id: string }>({ icon: Icon, items, label, render }: { icon: typeof History; items: T[]; label: string; render: (item: T) => React.ReactNode }) {
  return <section className="premium-panel rounded-lg p-5"><div className="flex items-center gap-2"><Icon aria-hidden="true" className="h-4 w-4 text-blue-200" /><h2 className="text-h4 font-semibold text-white">{label}</h2></div><div className="mt-5 grid gap-4">{items.length ? items.slice(0, 5).map((item) => <div className="grid gap-1 border-b border-border pb-4 last:border-0 last:pb-0" key={item.id}>{render(item)}</div>) : <p className="text-small text-neutral-400">No saved {label.toLowerCase()} yet.</p>}</div></section>;
}

function NextPageLink({ href }: { href: string | null }) {
  if (!href) return null;
  return <Link className="mt-5 inline-flex items-center gap-2 text-caption font-semibold text-blue-200 hover:text-white" href={href}>Load next page <ArrowRight aria-hidden="true" className="h-3.5 w-3.5" /></Link>;
}

export function AnalysisHistoryCollection({ data, nextHref }: { data: HistoryWorkspace; nextHref: string | null }) {
  const companyNames = new Map(data.companies.items.map((company) => [company.id, company.name]));
  return <section className="open-section"><div className="mb-6"><p className="premium-kicker">Analysis history</p><h1 className="mt-2 text-h2 font-semibold text-white">Immutable analysis results</h1><p className="mt-2 text-small leading-6 text-neutral-400">Opening a historical run uses the stored result and exact dataset version associated with that run. It is never silently recalculated from current company data.</p></div>{data.analyses.items.length ? <div className="overflow-x-auto border-y border-border"><table className="min-w-[44rem] w-full text-left text-small"><thead className="text-caption uppercase tracking-[0.08em] text-neutral-500"><tr><th className="px-3 py-3">Company</th><th className="px-3 py-3">Dataset</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Date</th><th className="px-3 py-3"><span className="sr-only">Open</span></th></tr></thead><tbody>{data.analyses.items.map((analysis) => <tr className="border-t border-border" key={analysis.id}><td className="px-3 py-4 font-semibold text-white">{companyNames.get(analysis.companyId) ?? "Archived company"}</td><td className="px-3 py-4 font-mono text-caption text-neutral-300">Version lineage retained</td><td className="px-3 py-4 text-neutral-300">{analysis.status}</td><td className="px-3 py-4 text-neutral-400">{formatWorkspaceDate(analysis.createdAt)}</td><td className="px-3 py-4"><OpenAnalysisLink runId={analysis.id} /></td></tr>)}</tbody></table></div> : <p className="premium-panel rounded-lg p-6 text-small text-neutral-400">No persisted analyses yet. Sign in, complete Financial Input and run an analysis to create history.</p>}<NextPageLink href={nextHref} /></section>;
}

export function FilesCollection({ data, nextHref }: { data: FilesWorkspace; nextHref: string | null }) {
  const companyNames = new Map(data.companies.items.map((company) => [company.id, company.name]));
  return <div className="grid gap-8"><section><p className="premium-kicker">Private files</p><h1 className="mt-2 text-h2 font-semibold text-white">Source documents, stored privately</h1><p className="mt-2 max-w-2xl text-small leading-6 text-neutral-400">Access is issued through short-lived signed links only after workspace authorization. Storage keys are never shown in the product.</p><div className="mt-6"><FileUploadForm companies={data.companies.items} /></div></section><section className="open-section">{data.files.items.length ? <div className="overflow-x-auto border-y border-border"><table className="min-w-[42rem] w-full text-left text-small"><thead className="text-caption uppercase tracking-[0.08em] text-neutral-500"><tr><th className="px-3 py-3">File</th><th className="px-3 py-3">Company</th><th className="px-3 py-3">Type</th><th className="px-3 py-3">Size</th><th className="px-3 py-3">Uploaded</th><th className="px-3 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody>{data.files.items.map((file) => <tr className="border-t border-border" key={file.id}><td className="max-w-64 truncate px-3 py-4 font-semibold text-white">{file.originalFilename}</td><td className="px-3 py-4 text-neutral-300">{file.companyId ? companyNames.get(file.companyId) ?? "Archived company" : "Workspace"}</td><td className="px-3 py-4 text-neutral-300">{file.mimeType}</td><td className="px-3 py-4 font-mono text-caption text-neutral-300">{Math.round(file.sizeBytes / 1024)} KB</td><td className="px-3 py-4 text-neutral-400">{formatWorkspaceDate(file.createdAt)}</td><td className="px-3 py-4"><FileActions fileId={file.id} /></td></tr>)}</tbody></table></div> : <p className="premium-panel rounded-lg p-6 text-small text-neutral-400">No private files yet. Upload a supported source document when it belongs with your financial work.</p>}<NextPageLink href={nextHref} /></section></div>;
}

export function ScenariosCollection({ data, nextHref }: { data: ScenariosWorkspace; nextHref: string | null }) {
  const companyNames = new Map(data.companies.items.map((company) => [company.id, company.name]));
  return <section className="open-section"><p className="premium-kicker">Saved scenarios</p><h1 className="mt-2 text-h2 font-semibold text-white">Scenario history with preserved lineage</h1><p className="mt-2 max-w-2xl text-small leading-6 text-neutral-400">Each saved scenario remains tied to the completed base analysis and immutable dataset version it used. It is a sensitivity record, never canonical financial truth.</p>{data.scenarios.items.length ? <div className="mt-6 grid divide-y divide-border border-y border-border">{data.scenarios.items.map((scenario) => <article className="grid gap-3 py-5 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center" key={scenario.id}><div><h2 className="text-h4 font-semibold text-white">{scenario.name}</h2><p className="mt-1 text-caption text-neutral-400">{companyNames.get(scenario.companyId) ?? "Archived company"} · {formatWorkspaceDate(scenario.createdAt)}</p></div><p className="max-w-sm text-caption text-neutral-400">{scenario.description ?? "Saved scenario assumptions and output."}</p><Link className="text-caption font-semibold text-blue-200 hover:text-white" href={`/workspace/scenarios/${scenario.id}`}>Open scenario</Link></article>)}</div> : <p className="premium-panel mt-6 rounded-lg p-6 text-small text-neutral-400">No scenarios are saved yet. Create one from Scenario Lab while signed in.</p>}<NextPageLink href={nextHref} /></section>;
}
