import type { FinancialAnalysisResult, MetricResult, RatioDefinition } from "@/domain";
import { formulaRegistry } from "@/domain/ratios";
import { formatCoverage, formatFinancialValue, valueFromMetric } from "@/features/executive-dashboard/lib/format-financial-value";

type LandingSignal = {
  label: string;
  value: string;
  state: string;
};

export type PremiumLandingViewModel = {
  company: string;
  industry: string;
  year: number;
  score: string;
  classification: string;
  coverage: string;
  signals: LandingSignal[];
  dimensions: Array<{ label: string; score: string; width: number }>;
  insights: string[];
  dupont: Array<{ label: string; value: string; description: string }>;
};

function ratio(result: FinancialAnalysisResult, id: string) {
  return result.currentPeriod.ratios[id];
}

function displayMetric(metric: MetricResult | undefined, definition: RatioDefinition, currency: "EUR" | "USD" | "GBP") {
  return formatFinancialValue({
    value: valueFromMetric(metric),
    unit: definition.unit,
    currency,
    unavailableReason: metric?.status === "unavailable" ? metric.reason : undefined,
  }).display;
}

export function buildPremiumLandingViewModel(result: FinancialAnalysisResult): PremiumLandingViewModel {
  const getDefinition = (id: string) => Object.values(formulaRegistry).find((definition) => definition.id === id)!;
  const score = result.score.total;
  const dupont = result.currentPeriod.dupont;

  return {
    company: result.company.name,
    industry: result.company.industry,
    year: result.currentPeriod.year,
    score: score === null ? "Unavailable" : formatFinancialValue({ value: score, unit: "score" }).display,
    classification: result.score.classification,
    coverage: formatCoverage(result.coverage.coveragePercentage),
    signals: [
      { label: "NOVATECH HEALTH", value: score === null ? "Unavailable" : formatFinancialValue({ value: score, unit: "score" }).display, state: result.score.classification.toUpperCase() },
      { label: "EBIT MARGIN", value: displayMetric(ratio(result, "ebit-margin"), getDefinition("ebit-margin"), result.company.currency), state: "OPERATING" },
      { label: "CURRENT RATIO", value: displayMetric(ratio(result, "current-ratio"), getDefinition("current-ratio"), result.company.currency), state: "LIQUIDITY" },
      { label: "RETURN ON EQUITY", value: displayMetric(ratio(result, "return-on-equity"), getDefinition("return-on-equity"), result.company.currency), state: "RETURN" },
      { label: "INTEREST COVERAGE", value: displayMetric(ratio(result, "interest-coverage"), getDefinition("interest-coverage"), result.company.currency), state: "SOLVENCY" },
      { label: "CASH CONVERSION", value: displayMetric(ratio(result, "cash-conversion-cycle"), getDefinition("cash-conversion-cycle"), result.company.currency), state: "WORKING CAPITAL" },
    ],
    dimensions: result.score.dimensions.map((dimension) => ({
      label: dimension.dimension === "cash-flow" ? "Cash Flow" : `${dimension.dimension.slice(0, 1).toUpperCase()}${dimension.dimension.slice(1)}`,
      score: dimension.score === null ? "Unavailable" : formatFinancialValue({ value: dimension.score, unit: "score" }).display,
      width: dimension.score === null ? 0 : Math.max(0, Math.min(100, dimension.score)),
    })),
    insights: result.principalInsights.strengths.concat(result.principalInsights.risks).slice(0, 3).map((insight) => insight.title),
    dupont: [
      { label: "Net Profit Margin", value: displayMetric(dupont.netProfitMargin, getDefinition("net-margin"), result.company.currency), description: "Earnings retained from revenue" },
      { label: "Asset Turnover", value: displayMetric(dupont.assetTurnover, getDefinition("asset-turnover"), result.company.currency), description: "Revenue generated by the asset base" },
      { label: "Financial Leverage", value: formatFinancialValue({ value: valueFromMetric(dupont.financialLeverage), unit: "multiple" }).display, description: "Asset support relative to equity" },
      { label: "Return on Equity", value: displayMetric(dupont.roe, getDefinition("return-on-equity"), result.company.currency), description: "Reconciled three-factor result" },
    ],
  };
}
