"use client";

import Link from "next/link";
import { useState } from "react";
import { BookOpen, Gauge, Network, SlidersHorizontal } from "lucide-react";

import { Button } from "@/components/ui/button";
import { ChartContainer, useReducedMotionPreference } from "@/features/executive-dashboard/charts/chart-container";
import { buildRatioTrendOption } from "@/features/executive-dashboard/charts/chart-options";
import type { RatioAnalysisViewModel } from "@/features/ratio-analysis/lib/build-ratio-analysis-view-model";
import type { RatioCategory } from "@/domain";

export function RatioAnalysis({ viewModel }: { viewModel: RatioAnalysisViewModel }) {
  const [category, setCategory] = useState<RatioCategory>(viewModel.defaultCategory);
  const [metricId, setMetricId] = useState(viewModel.trend.defaultMetricId);
  const metrics = viewModel.trend.metricsByCategory[category];
  const selected = viewModel.trend.metricsById[metricId] ?? metrics[0];
  const reducedMotion = useReducedMotionPreference();
  const group = viewModel.table.groups.find((item) => item.category === category);

  return <div className="grid min-w-0 gap-5">
    <section aria-label="Ratio analysis context" className="border border-border bg-surface p-4"><div className="flex flex-col gap-4"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-caption uppercase text-neutral-400">Company / Industry</p><p className="mt-1 text-body font-semibold text-neutral-50">{viewModel.company.name}</p><p className="text-small text-neutral-400">{viewModel.company.industry}</p></div><div className="flex flex-wrap gap-x-5 gap-y-3 text-small"><Context label="Current period" value={String(viewModel.period.current)} /><Context label="Comparison" value={viewModel.period.previous ? String(viewModel.period.previous) : "Unavailable"} /><Context label="Currency" value={viewModel.company.currency} /><Context label="Coverage" value={`${viewModel.coverage.toFixed(0)}%`} /></div></div><div className="flex flex-wrap gap-3 border-t border-border pt-4"><Action href="/analysis" icon={Gauge} label="Executive Dashboard" /><Action href="/analysis/dupont" icon={Network} label="DuPont Analysis" /><Action href="/scenario" icon={SlidersHorizontal} label="Scenario Lab" /><Action href="/methodology" icon={BookOpen} label="Methodology" /></div></div></section>
    <section className="border border-border bg-surface p-4 md:p-5"><p className="text-caption uppercase text-neutral-400">Ratio overview</p><h2 className="mt-1 text-h4 font-semibold text-neutral-50">Registered financial ratios</h2><p className="mt-2 text-small text-neutral-300">{viewModel.availability} of {viewModel.configured} registered outputs are available. Unavailable means an input or denominator was unsuitable; it never means zero.</p><div aria-label="Ratio categories" className="mt-4 flex flex-wrap gap-2">{viewModel.categories.map((item) => <button aria-pressed={item.id === category} className={`border px-3 py-2 text-small focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary ${item.id === category ? "border-primary bg-primary/10 text-neutral-50" : "border-border text-neutral-300"}`} key={item.id} onClick={() => { setCategory(item.id); setMetricId(viewModel.trend.metricsByCategory[item.id][0]?.metricId ?? viewModel.trend.defaultMetricId); }} type="button">{item.label} <span className="font-mono text-caption">{item.count}</span></button>)}</div></section>
    <section aria-label="Ratio trend analysis" className="border border-border bg-surface p-4 md:p-5"><div className="grid gap-3 sm:grid-cols-2"><Select label="Ratio category" onChange={(next) => { const nextCategory = next as RatioCategory; setCategory(nextCategory); setMetricId(viewModel.trend.metricsByCategory[nextCategory][0]?.metricId ?? viewModel.trend.defaultMetricId); }} options={viewModel.categories.map((item) => ({ value: item.id, label: item.label }))} value={category} /><Select label="Ratio metric" onChange={setMetricId} options={metrics.map((item) => ({ value: item.metricId, label: item.label }))} value={selected.metricId} /></div><ChartContainer accessibleDescription={selected.accessibleDescription} accessibleName={`${selected.label} trend`} heightClassName="h-52" option={buildRatioTrendOption(selected, reducedMotion)} summary={<div className="mt-3 grid gap-2 text-small text-neutral-300 sm:grid-cols-3"><p><b>Current:</b> {selected.currentValue.display}</p><p><b>Previous:</b> {selected.previousValue.display}</p><p><b>Change:</b> {selected.change.display}</p><p><b>Movement:</b> {viewModel.financialDirection(selected.metricId, selected.direction)}</p><p className="sm:col-span-2">{selected.summary}</p></div>} /></section>
    <section aria-label="Detailed ratio table" className="min-w-0 border border-border bg-surface p-4 md:p-5"><p className="text-caption uppercase text-neutral-400">Detailed inspection</p><h2 className="mt-1 text-h4 font-semibold text-neutral-50">{group?.label} ratios</h2><div className="mt-4 max-w-full overflow-x-auto border border-border"><table className="min-w-[980px] border-collapse text-left text-caption"><thead className="bg-background/60 text-neutral-300"><tr>{["Ratio", "Current", "Previous", "Change", "Financial direction", "Availability", "Formula and interpretation"].map((heading) => <th className="border-b border-border px-3 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{group?.rows.map((row) => <tr className="align-top" key={row.label}><td className="px-3 py-3 font-semibold text-neutral-50">{row.label}</td><td className="px-3 py-3 font-mono tabular-nums">{row.currentValue.display}</td><td className="px-3 py-3 font-mono tabular-nums">{row.previousValue.display}</td><td className="px-3 py-3 font-mono tabular-nums">{row.change.display}</td><td className="px-3 py-3">{viewModel.financialDirection(row.label.toLowerCase().replaceAll(" ", "-"), row.direction)}</td><td className="px-3 py-3">{row.availability}{row.unavailableReason ? <span className="block text-neutral-500">{row.unavailableReason}</span> : null}</td><td className="px-3 py-3"><details><summary className="cursor-pointer font-semibold text-neutral-100">Formula and interpretation</summary><p className="mt-2 font-mono text-neutral-200">{row.formula}</p><p className="mt-2 text-neutral-300">{row.interpretation}</p><p className="mt-2 text-neutral-400">{row.description}</p></details></td></tr>)}</tbody></table></div><p className="mt-3 text-caption text-neutral-400">Formula metadata, units and unavailable conditions are supplied by the registered financial-ratio definitions.</p></section>
  </div>;
}
function Context({ label, value }: { label: string; value: string }) { return <p><span className="block uppercase text-neutral-400">{label}</span><span className="font-mono font-semibold tabular-nums text-neutral-50">{value}</span></p>; }
function Action({ href, icon: Icon, label }: { href: string; icon: typeof Gauge; label: string }) { return <Button asChild variant="secondary"><Link href={href}><Icon aria-hidden="true" className="h-4 w-4" />{label}</Link></Button>; }
function Select({ label, onChange, options, value }: { label: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }>; value: string }) { return <label className="grid gap-2 text-small font-semibold text-neutral-100">{label}<select className="min-h-11 border border-border bg-background px-3 text-neutral-50" onChange={(event) => onChange(event.target.value)} value={value}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
