"use client";
import { useEffect, useState } from "react";
import { ACTIVE_ANALYSIS_STORAGE_KEY } from "@/features/financial-input/persistence";
import { DashboardEmpty, DashboardError, DashboardLoading } from "@/features/executive-dashboard/components/dashboard-state";
import { recoverExecutiveDashboardSession } from "@/features/executive-dashboard/lib/recover-analysis-session";
import { RatioAnalysis } from "@/features/ratio-analysis/components/ratio-analysis";
import type { DashboardSessionRecoveryResult } from "@/features/executive-dashboard/types/dashboard.types";
import type { ExecutiveDashboardViewModel } from "@/features/executive-dashboard/types/dashboard.types";
import type { RatioAnalysisViewModel } from "@/features/ratio-analysis/lib/build-ratio-analysis-view-model";
type State = { status: "loading" } | DashboardSessionRecoveryResult;
export function RatioAnalysisSessionBoundary() { const [state, setState] = useState<State>({ status: "loading" }); useEffect(() => { const timer = setTimeout(() => setState(recoverExecutiveDashboardSession(sessionStorage.getItem(ACTIVE_ANALYSIS_STORAGE_KEY))), 0); return () => clearTimeout(timer); }, []); if (state.status === "loading") return <DashboardLoading />; if (state.status === "empty") return <DashboardEmpty />; if (state.status === "ready") return <RatioAnalysis viewModel={buildRatioAnalysisViewModelFromDashboard(state.viewModel)} />; return <DashboardError title={state.status === "analysis-error" ? "Ratio analysis could not be completed" : "Ratio analysis session could not be read"} message={state.message} />; }
function buildRatioAnalysisViewModelFromDashboard(viewModel: ExecutiveDashboardViewModel): RatioAnalysisViewModel { return { company: viewModel.company, period: { current: viewModel.period.currentYear, previous: viewModel.period.comparisonYear }, coverage: viewModel.coverage.value, categories: viewModel.ratioTable.groups.map((group) => ({ id: group.category, label: group.label, count: group.rows.length })), defaultCategory: viewModel.ratioTrend.defaultCategory, table: viewModel.ratioTable, trend: viewModel.ratioTrend, availability: viewModel.ratioTable.groups.reduce((total, group) => total + group.rows.filter((row) => row.availability === "Available").length, 0), configured: viewModel.ratioTable.groups.reduce((total, group) => total + group.rows.length, 0), financialDirection: (metricId: string, movement: string) => { const lower = new Set(["debt-to-equity", "debt-to-assets", "days-sales-outstanding", "days-inventory-outstanding", "cash-conversion-cycle"]); if (movement === "Unavailable") return "Movement unavailable"; if (movement === "Unchanged") return "Neutral movement"; return (lower.has(metricId) ? movement === "Decreased" : movement === "Increased") ? "Favourable movement" : "Unfavourable movement"; } }; }
