import type { FinancialSectionId, WorkflowStepId } from "@/features/financial-input/types";

export const workflowSteps: Array<{
  id: WorkflowStepId;
  label: string;
}> = [
  { id: "company", label: "Company" },
  { id: "income-statement", label: "Income Statement" },
  { id: "balance-sheet", label: "Balance Sheet" },
  { id: "cash-flow", label: "Cash Flow" },
  { id: "working-capital", label: "Working Capital" },
  { id: "review", label: "Review" },
];

export const sectionLabels: Record<WorkflowStepId, string> = {
  company: "Company",
  "income-statement": "Income Statement",
  "balance-sheet": "Balance Sheet",
  "cash-flow": "Cash Flow",
  "working-capital": "Working Capital",
  review: "Review",
};

export type FinancialFieldMetadata = {
  key: string;
  label: string;
  description: string;
  helperText?: string;
  pathPrefix: FinancialSectionId;
  allowNegative: boolean;
};

export const financialFieldGroups: Record<FinancialSectionId, FinancialFieldMetadata[]> = {
  "income-statement": [
    {
      key: "revenue",
      label: "Revenue",
      description: "Total annual sales before costs.",
      pathPrefix: "income-statement",
      allowNegative: false,
    },
    {
      key: "costOfGoodsSold",
      label: "Cost of Goods Sold",
      description: "Direct costs associated with revenue.",
      pathPrefix: "income-statement",
      allowNegative: false,
    },
    {
      key: "ebit",
      label: "EBIT",
      description: "Operating profit before interest and taxes.",
      pathPrefix: "income-statement",
      allowNegative: true,
    },
    {
      key: "interestExpense",
      label: "Interest Expense",
      description: "Annual financing cost.",
      pathPrefix: "income-statement",
      allowNegative: false,
    },
    {
      key: "netIncome",
      label: "Net Income",
      description: "Profit after interest and taxes.",
      pathPrefix: "income-statement",
      allowNegative: true,
    },
  ],
  "balance-sheet": [
    {
      key: "cash",
      label: "Cash",
      description: "Cash and cash equivalents.",
      pathPrefix: "balance-sheet",
      allowNegative: true,
    },
    {
      key: "accountsReceivable",
      label: "Accounts Receivable",
      description: "Amounts owed by customers.",
      pathPrefix: "balance-sheet",
      allowNegative: true,
    },
    {
      key: "inventory",
      label: "Inventory",
      description: "Inventory balance at year end.",
      pathPrefix: "balance-sheet",
      allowNegative: true,
    },
    {
      key: "currentAssets",
      label: "Current Assets",
      description: "Assets expected to convert within one year.",
      pathPrefix: "balance-sheet",
      allowNegative: true,
    },
    {
      key: "totalAssets",
      label: "Total Assets",
      description: "Total asset base at year end.",
      pathPrefix: "balance-sheet",
      allowNegative: true,
    },
    {
      key: "currentLiabilities",
      label: "Current Liabilities",
      description: "Obligations due within one year.",
      pathPrefix: "balance-sheet",
      allowNegative: true,
    },
    {
      key: "totalDebt",
      label: "Total Debt",
      description: "Interest-bearing debt.",
      pathPrefix: "balance-sheet",
      allowNegative: true,
    },
    {
      key: "equity",
      label: "Equity",
      description: "Book value of shareholders' equity.",
      pathPrefix: "balance-sheet",
      allowNegative: true,
    },
  ],
  "cash-flow": [
    {
      key: "operatingCashFlow",
      label: "Operating Cash Flow",
      description: "Cash generated by operations.",
      pathPrefix: "cash-flow",
      allowNegative: true,
    },
    {
      key: "capitalExpenditure",
      label: "Capital Expenditure",
      description: "Investment in long-term assets.",
      helperText: "Enter CapEx as a positive expenditure. Free Cash Flow is calculated as OCF minus CapEx.",
      pathPrefix: "cash-flow",
      allowNegative: false,
    },
  ],
  "working-capital": [
    {
      key: "averageInventory",
      label: "Average Inventory",
      description: "Average inventory balance for the financial year.",
      helperText: "Use average balances for the financial year.",
      pathPrefix: "working-capital",
      allowNegative: true,
    },
    {
      key: "averageReceivables",
      label: "Average Receivables",
      description: "Average receivables balance for the financial year.",
      helperText: "Use average balances for the financial year.",
      pathPrefix: "working-capital",
      allowNegative: true,
    },
    {
      key: "averagePayables",
      label: "Average Payables",
      description: "Average payables balance for the financial year.",
      helperText: "Use average balances for the financial year.",
      pathPrefix: "working-capital",
      allowNegative: true,
    },
  ],
};

export function getStepIndex(stepId: WorkflowStepId) {
  return workflowSteps.findIndex((step) => step.id === stepId);
}

export function getNextStep(stepId: WorkflowStepId): WorkflowStepId {
  const index = getStepIndex(stepId);
  return workflowSteps[Math.min(index + 1, workflowSteps.length - 1)].id;
}

export function getPreviousStep(stepId: WorkflowStepId): WorkflowStepId {
  const index = getStepIndex(stepId);
  return workflowSteps[Math.max(index - 1, 0)].id;
}
