import type { FinancialPeriod, MetricResult, RatioDefinition } from "@/domain/types";

import {
  calculateEbitMargin,
  calculateGrossMargin,
  calculateGrossProfit,
  calculateNetMargin,
  calculateReturnOnAssets,
  calculateReturnOnCapitalEmployed,
  calculateReturnOnEquity,
} from "@/domain/ratios/profitability";
import {
  calculateCashRatio,
  calculateCurrentRatio,
  calculateOperatingCashFlowRatio,
  calculateQuickRatio,
} from "@/domain/ratios/liquidity";
import {
  calculateDebtToAssets,
  calculateDebtToEquity,
  calculateEquityRatio,
  calculateInterestCoverage,
} from "@/domain/ratios/solvency";
import {
  calculateAssetTurnover,
  calculateCashConversionCycle,
  calculateDaysInventoryOutstanding,
  calculateDaysPayablesOutstanding,
  calculateDaysSalesOutstanding,
  calculateInventoryTurnover,
  calculateReceivablesTurnover,
} from "@/domain/ratios/efficiency";
import {
  calculateFreeCashFlow,
  calculateFreeCashFlowMargin,
  calculateOperatingCashFlowMargin,
  calculateOperatingCashFlowToNetIncome,
} from "@/domain/ratios/cash-flow";

export type RatioCalculationFunction = (period: FinancialPeriod, previousPeriod?: FinancialPeriod) => MetricResult;

export type FormulaDefinition = RatioDefinition & {
  calculate: RatioCalculationFunction;
};

export const formulaRegistry = {
  "gross-profit": {
    id: "gross-profit",
    name: "Gross Profit",
    shortName: "Gross Profit",
    category: "profitability",
    unit: "currency",
    description: "Revenue remaining after cost of goods sold.",
    formulaLabel: "Revenue - Cost of Goods Sold",
    inputs: ["revenue", "costOfGoodsSold"],
    interpretation: "Higher gross profit indicates more revenue remains to fund operating costs and profit.",
    unavailableConditions: ["Unavailable when required inputs are missing or non-finite."],
    scoreEligible: false,
    calculate: calculateGrossProfit,
  },
  "gross-margin": {
    id: "gross-margin",
    name: "Gross Margin",
    shortName: "Gross Margin",
    category: "profitability",
    unit: "percentage",
    description: "Percentage of revenue remaining after cost of goods sold.",
    formulaLabel: "(Revenue - Cost of Goods Sold) / Revenue",
    inputs: ["revenue", "costOfGoodsSold"],
    interpretation: "Higher gross margin indicates stronger direct profitability.",
    unavailableConditions: ["Revenue is zero.", "Revenue is negative and non-meaningful for this margin."],
    scoreEligible: true,
    calculate: calculateGrossMargin,
  },
  "ebit-margin": {
    id: "ebit-margin",
    name: "EBIT Margin",
    shortName: "EBIT Margin",
    category: "profitability",
    unit: "percentage",
    description: "Operating profit before interest and taxes as a percentage of revenue.",
    formulaLabel: "EBIT / Revenue",
    inputs: ["ebit", "revenue"],
    interpretation: "Higher EBIT margin indicates stronger operating profitability.",
    unavailableConditions: ["Revenue is zero.", "Revenue is negative and non-meaningful for this margin."],
    scoreEligible: true,
    calculate: calculateEbitMargin,
  },
  "net-margin": {
    id: "net-margin",
    name: "Net Margin",
    shortName: "Net Margin",
    category: "profitability",
    unit: "percentage",
    description: "Net income as a percentage of revenue.",
    formulaLabel: "Net Income / Revenue",
    inputs: ["netIncome", "revenue"],
    interpretation: "Higher net margin indicates more revenue converts into final profit.",
    unavailableConditions: ["Revenue is zero.", "Revenue is negative and non-meaningful for this margin."],
    scoreEligible: true,
    calculate: calculateNetMargin,
  },
  "return-on-assets": {
    id: "return-on-assets",
    name: "Return on Assets",
    shortName: "ROA",
    category: "profitability",
    unit: "percentage",
    description: "Net income generated per unit of average total assets.",
    formulaLabel: "Net Income / Average Total Assets",
    inputs: ["netIncome", "totalAssets", "previousPeriod.totalAssets"],
    interpretation: "Higher ROA indicates more effective asset use.",
    unavailableConditions: ["Average total assets are zero or negative."],
    scoreEligible: true,
    calculate: calculateReturnOnAssets,
  },
  "return-on-equity": {
    id: "return-on-equity",
    name: "Return on Equity",
    shortName: "ROE",
    category: "profitability",
    unit: "percentage",
    description: "Net income generated per unit of average equity.",
    formulaLabel: "Net Income / Average Equity",
    inputs: ["netIncome", "equity", "previousPeriod.equity"],
    interpretation: "Higher ROE indicates stronger returns to equity holders, subject to leverage context.",
    unavailableConditions: ["Average equity is zero or negative."],
    scoreEligible: true,
    calculate: calculateReturnOnEquity,
  },
  "return-on-capital-employed": {
    id: "return-on-capital-employed",
    name: "Return on Capital Employed",
    shortName: "ROCE",
    category: "profitability",
    unit: "percentage",
    description: "EBIT generated per unit of average capital employed.",
    formulaLabel: "EBIT / Average Capital Employed",
    inputs: ["ebit", "totalAssets", "currentLiabilities", "previousPeriod.totalAssets", "previousPeriod.currentLiabilities"],
    interpretation: "Higher ROCE indicates stronger operating returns on deployed capital.",
    unavailableConditions: ["Average capital employed is zero or negative."],
    scoreEligible: true,
    calculate: calculateReturnOnCapitalEmployed,
  },
  "current-ratio": {
    id: "current-ratio",
    name: "Current Ratio",
    shortName: "Current Ratio",
    category: "liquidity",
    unit: "multiple",
    description: "Current assets available for each unit of current liabilities.",
    formulaLabel: "Current Assets / Current Liabilities",
    inputs: ["currentAssets", "currentLiabilities"],
    interpretation: "Higher values indicate more short-term asset coverage.",
    unavailableConditions: ["Current liabilities are zero or negative."],
    scoreEligible: true,
    calculate: calculateCurrentRatio,
  },
  "quick-ratio": {
    id: "quick-ratio",
    name: "Quick Ratio",
    shortName: "Quick Ratio",
    category: "liquidity",
    unit: "multiple",
    description: "Liquid current assets available for each unit of current liabilities.",
    formulaLabel: "(Current Assets - Inventory) / Current Liabilities",
    inputs: ["currentAssets", "inventory", "currentLiabilities"],
    interpretation: "Higher values indicate stronger near-cash liquidity.",
    unavailableConditions: ["Current liabilities are zero or negative."],
    scoreEligible: true,
    calculate: calculateQuickRatio,
  },
  "cash-ratio": {
    id: "cash-ratio",
    name: "Cash Ratio",
    shortName: "Cash Ratio",
    category: "liquidity",
    unit: "multiple",
    description: "Cash available for each unit of current liabilities.",
    formulaLabel: "Cash / Current Liabilities",
    inputs: ["cash", "currentLiabilities"],
    interpretation: "Higher values indicate stronger immediate liquidity.",
    unavailableConditions: ["Current liabilities are zero or negative."],
    scoreEligible: true,
    calculate: calculateCashRatio,
  },
  "operating-cash-flow-ratio": {
    id: "operating-cash-flow-ratio",
    name: "Operating Cash Flow Ratio",
    shortName: "OCF Ratio",
    category: "liquidity",
    unit: "multiple",
    description: "Operating cash flow available for each unit of current liabilities.",
    formulaLabel: "Operating Cash Flow / Current Liabilities",
    inputs: ["operatingCashFlow", "currentLiabilities"],
    interpretation: "Higher values indicate stronger cash-based short-term coverage.",
    unavailableConditions: ["Current liabilities are zero or negative."],
    scoreEligible: true,
    calculate: calculateOperatingCashFlowRatio,
  },
  "debt-to-equity": {
    id: "debt-to-equity",
    name: "Debt-to-Equity",
    shortName: "D/E",
    category: "solvency",
    unit: "multiple",
    description: "Debt financing relative to equity financing.",
    formulaLabel: "Total Debt / Equity",
    inputs: ["totalDebt", "equity"],
    interpretation: "Lower values generally indicate less financial leverage.",
    unavailableConditions: ["Equity is zero or negative."],
    scoreEligible: true,
    calculate: calculateDebtToEquity,
  },
  "debt-to-assets": {
    id: "debt-to-assets",
    name: "Debt-to-Assets",
    shortName: "Debt/Assets",
    category: "solvency",
    unit: "percentage",
    description: "Share of assets financed by debt.",
    formulaLabel: "Total Debt / Total Assets",
    inputs: ["totalDebt", "totalAssets"],
    interpretation: "Lower values generally indicate lower balance-sheet leverage.",
    unavailableConditions: ["Total assets are zero or negative."],
    scoreEligible: true,
    calculate: calculateDebtToAssets,
  },
  "equity-ratio": {
    id: "equity-ratio",
    name: "Equity Ratio",
    shortName: "Equity Ratio",
    category: "solvency",
    unit: "percentage",
    description: "Share of assets financed by equity.",
    formulaLabel: "Equity / Total Assets",
    inputs: ["equity", "totalAssets"],
    interpretation: "Higher values generally indicate a stronger equity buffer.",
    unavailableConditions: ["Total assets are zero or negative."],
    scoreEligible: true,
    calculate: calculateEquityRatio,
  },
  "interest-coverage": {
    id: "interest-coverage",
    name: "Interest Coverage",
    shortName: "Interest Coverage",
    category: "solvency",
    unit: "multiple",
    description: "EBIT available for each unit of interest expense.",
    formulaLabel: "EBIT / Interest Expense",
    inputs: ["ebit", "interestExpense"],
    interpretation: "Higher values indicate stronger capacity to service interest.",
    unavailableConditions: ["Interest expense is zero or negative."],
    scoreEligible: true,
    calculate: calculateInterestCoverage,
  },
  "asset-turnover": {
    id: "asset-turnover",
    name: "Asset Turnover",
    shortName: "Asset Turnover",
    category: "efficiency",
    unit: "multiple",
    description: "Revenue generated per unit of average total assets.",
    formulaLabel: "Revenue / Average Total Assets",
    inputs: ["revenue", "totalAssets", "previousPeriod.totalAssets"],
    interpretation: "Higher values indicate more efficient use of assets to generate revenue.",
    unavailableConditions: ["Average total assets are zero or negative."],
    scoreEligible: true,
    calculate: calculateAssetTurnover,
  },
  "inventory-turnover": {
    id: "inventory-turnover",
    name: "Inventory Turnover",
    shortName: "Inventory Turnover",
    category: "efficiency",
    unit: "multiple",
    description: "Cost of goods sold generated per unit of average inventory.",
    formulaLabel: "Cost of Goods Sold / Average Inventory",
    inputs: ["costOfGoodsSold", "averageInventory"],
    interpretation: "Higher values indicate inventory is converted into sales more quickly.",
    unavailableConditions: ["Average inventory is zero or negative."],
    scoreEligible: true,
    calculate: calculateInventoryTurnover,
  },
  "receivables-turnover": {
    id: "receivables-turnover",
    name: "Receivables Turnover",
    shortName: "Receivables Turnover",
    category: "efficiency",
    unit: "multiple",
    description: "Revenue generated per unit of average receivables.",
    formulaLabel: "Revenue / Average Receivables",
    inputs: ["revenue", "averageReceivables"],
    interpretation: "Higher values indicate receivables are collected more quickly.",
    unavailableConditions: ["Average receivables are zero or negative."],
    scoreEligible: true,
    calculate: calculateReceivablesTurnover,
  },
  "days-sales-outstanding": {
    id: "days-sales-outstanding",
    name: "Days Sales Outstanding",
    shortName: "DSO",
    category: "efficiency",
    unit: "days",
    description: "Average number of days revenue remains in receivables.",
    formulaLabel: "Average Receivables / Revenue * 365",
    inputs: ["averageReceivables", "revenue"],
    interpretation: "Lower values indicate faster receivables collection.",
    unavailableConditions: ["Revenue is zero or negative."],
    scoreEligible: true,
    calculate: calculateDaysSalesOutstanding,
  },
  "days-inventory-outstanding": {
    id: "days-inventory-outstanding",
    name: "Days Inventory Outstanding",
    shortName: "DIO",
    category: "efficiency",
    unit: "days",
    description: "Average number of days inventory is held before sale.",
    formulaLabel: "Average Inventory / Cost of Goods Sold * 365",
    inputs: ["averageInventory", "costOfGoodsSold"],
    interpretation: "Lower values indicate faster inventory conversion.",
    unavailableConditions: ["Cost of goods sold is zero or negative."],
    scoreEligible: true,
    calculate: calculateDaysInventoryOutstanding,
  },
  "days-payables-outstanding": {
    id: "days-payables-outstanding",
    name: "Days Payables Outstanding",
    shortName: "DPO",
    category: "efficiency",
    unit: "days",
    description: "Average number of days payables remain outstanding.",
    formulaLabel: "Average Payables / Cost of Goods Sold * 365",
    inputs: ["averagePayables", "costOfGoodsSold"],
    interpretation: "Higher values indicate the company takes longer to pay suppliers.",
    unavailableConditions: ["Cost of goods sold is zero or negative."],
    scoreEligible: true,
    calculate: calculateDaysPayablesOutstanding,
  },
  "cash-conversion-cycle": {
    id: "cash-conversion-cycle",
    name: "Cash Conversion Cycle",
    shortName: "CCC",
    category: "efficiency",
    unit: "days",
    description: "Time between cash invested in working capital and cash collected from customers.",
    formulaLabel: "DIO + DSO - DPO",
    inputs: ["DIO", "DSO", "DPO"],
    interpretation: "Lower values indicate a shorter working-capital cash cycle.",
    unavailableConditions: ["Any required DIO, DSO or DPO component is unavailable."],
    scoreEligible: true,
    calculate: calculateCashConversionCycle,
  },
  "operating-cash-flow-margin": {
    id: "operating-cash-flow-margin",
    name: "Operating Cash Flow Margin",
    shortName: "OCF Margin",
    category: "cash-flow",
    unit: "percentage",
    description: "Operating cash flow generated per unit of revenue.",
    formulaLabel: "Operating Cash Flow / Revenue",
    inputs: ["operatingCashFlow", "revenue"],
    interpretation: "Higher values indicate stronger cash conversion from sales.",
    unavailableConditions: ["Revenue is zero or negative."],
    scoreEligible: true,
    calculate: calculateOperatingCashFlowMargin,
  },
  "free-cash-flow": {
    id: "free-cash-flow",
    name: "Free Cash Flow",
    shortName: "FCF",
    category: "cash-flow",
    unit: "currency",
    description: "Cash remaining after capital expenditure.",
    formulaLabel: "Operating Cash Flow - Capital Expenditure",
    inputs: ["operatingCashFlow", "capitalExpenditure"],
    interpretation: "Higher values indicate more discretionary cash generation after reinvestment.",
    unavailableConditions: ["Unavailable when required inputs are missing or non-finite."],
    scoreEligible: true,
    calculate: calculateFreeCashFlow,
  },
  "free-cash-flow-margin": {
    id: "free-cash-flow-margin",
    name: "Free Cash Flow Margin",
    shortName: "FCF Margin",
    category: "cash-flow",
    unit: "percentage",
    description: "Free cash flow generated per unit of revenue.",
    formulaLabel: "(Operating Cash Flow - Capital Expenditure) / Revenue",
    inputs: ["operatingCashFlow", "capitalExpenditure", "revenue"],
    interpretation: "Higher values indicate stronger post-investment cash generation from sales.",
    unavailableConditions: ["Revenue is zero or negative."],
    scoreEligible: true,
    calculate: calculateFreeCashFlowMargin,
  },
  "operating-cash-flow-to-net-income": {
    id: "operating-cash-flow-to-net-income",
    name: "Operating Cash Flow to Net Income",
    shortName: "OCF/NI",
    category: "cash-flow",
    unit: "multiple",
    description: "Operating cash flow compared with net income.",
    formulaLabel: "Operating Cash Flow / Net Income",
    inputs: ["operatingCashFlow", "netIncome"],
    interpretation: "Values above one indicate cash flow exceeds accounting earnings.",
    unavailableConditions: ["Net income is zero."],
    scoreEligible: true,
    calculate: calculateOperatingCashFlowToNetIncome,
  },
} as const satisfies Record<string, FormulaDefinition>;

export type FormulaId = keyof typeof formulaRegistry;
