import Link from "next/link";
import { BookOpen, Database, ExternalLink, FileWarning, Sigma } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { buildMethodologyViewModel } from "@/features/methodology/lib/build-methodology-view-model";

const model = buildMethodologyViewModel();
const sections = ["Input model", "Formula catalogue", "Health Score", "Missing data", "Insights", "DuPont", "Scenarios", "Limitations"];

export function Methodology() {
  return <div className="grid min-w-0 gap-6">
    <section className="border-b border-border pb-6"><Badge variant="info">Transparent methodology</Badge><h2 className="mt-3 text-h2 font-semibold text-neutral-50">Financial analysis that can be inspected</h2><p className="mt-2 max-w-3xl text-body text-neutral-300">The application validates three annual financial statements, calculates registered ratios through deterministic domain logic, then presents transparent score, DuPont and scenario outputs.</p><nav aria-label="Methodology sections" className="mt-4 flex flex-wrap gap-2">{sections.map((section) => <a className="border border-border px-3 py-2 text-caption text-neutral-300 hover:text-neutral-50" href={`#${section.toLowerCase().replaceAll(" ", "-")}`} key={section}>{section}</a>)}</nav></section>
    <MethodSection id="input-model" icon={Database} title="Financial input model"><p>Company context and exactly three chronological annual periods form a canonical <b>FinancialAnalysisInput</b>. Browser fields remain strings until explicit parsing; blank input is required, never silently treated as zero. Canonical validation requires supported currency, finite values and a strict three-period structure.</p></MethodSection>
    <MethodSection id="formula-catalogue" icon={Sigma} title={`Formula catalogue (${model.formulaCount} registered outputs)`}><p>Each item below comes from the implemented formula registry. Availability conditions are preserved with every result.</p><div className="mt-4 grid gap-3">{model.dimensions.map((dimension) => <details className="border border-border bg-background/30 p-4" key={dimension.id}><summary className="cursor-pointer font-semibold text-neutral-50">{dimension.label}</summary><div className="mt-4 grid gap-3">{model.formulas.filter((formula) => formula.category === dimension.id).map((formula) => <details className="border-l-2 border-primary/70 pl-3" key={formula.id}><summary className="cursor-pointer text-small font-semibold text-neutral-50">{formula.name} <span className="font-normal text-neutral-400">({formula.unit})</span></summary><p className="mt-2 font-mono text-caption text-neutral-200">{formula.formulaLabel}</p><p className="mt-2 text-small text-neutral-300">{formula.description}</p><p className="mt-2 text-caption text-neutral-400"><b>Interpretation:</b> {formula.interpretation}</p><p className="mt-1 text-caption text-neutral-400"><b>Direction:</b> {formula.direction}</p><p className="mt-1 text-caption text-neutral-400"><b>Unavailable:</b> {formula.unavailableConditions.join(" ")}</p></details>)}</div></details>)}</div></MethodSection>
    <MethodSection id="health-score" icon={Sigma} title="Financial Health Score"><p>The 0–100 Financial Health Score is a generic educational assessment. It combines available registered metrics across five dimensions with validated, anchor-based piecewise linear interpolation. Values outside an anchor range use the nearest endpoint score; internal calculation values are not rounded.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{model.dimensions.map((dimension) => <div className="border border-border bg-background/30 p-4" key={dimension.id}><p className="font-semibold text-neutral-50">{dimension.label} <span className="font-mono text-neutral-300">{(dimension.weight * 100).toFixed(0)}%</span></p><ul className="mt-2 grid gap-1 text-caption text-neutral-300">{dimension.metrics.map((metric) => <li key={metric.label}>{metric.label}: {(metric.weight * 100).toFixed(0)}% · {metric.threshold.mode}</li>)}</ul></div>)}</div><p className="mt-4 text-small text-neutral-300">Classification: Strong 80–100; Healthy 65–&lt;80; Moderate 50–&lt;65; Weak 35–&lt;50; Critical 0–&lt;35; Unavailable when scoring requirements are unmet.</p></MethodSection>
    <MethodSection id="missing-data" icon={FileWarning} title="Coverage and missing data"><p>Unavailable is not zero. Safe division rejects unsuitable denominators and returns a typed unavailable result. Available metrics are reweighted only within their dimension; a dimension needs at least 60% weighted coverage and two available metrics. A total score needs at least 70% analytical coverage and four available dimensions.</p></MethodSection>
    <MethodSection id="insights" icon={BookOpen} title="Deterministic insight methodology"><p>Strengths, risks and observations are generated from fixed rules and structured financial evidence. Every insight carries severity, trend, priority, affected year and supporting metrics. Principal insights use stable deterministic ordering. No generative AI, probabilistic confidence or investment recommendation is used.</p></MethodSection>
    <MethodSection id="dupont" icon={Sigma} title="DuPont and ROE attribution"><p><b>ROE = Net Profit Margin × Asset Turnover × Financial Leverage.</b> Average balances use the prior period when available and the documented closing-balance fallback for the oldest period. Identity reconciliation is separate from current-versus-prior attribution. Attribution averages marginal contributions across all six factor substitution orders, reports percentage points, uses a documented tolerance and assigns no hidden residual. Leverage is contextual: it can amplify strong or weak operating performance.</p></MethodSection>
    <MethodSection id="scenarios" icon={Database} title="Scenario methodology"><p>Base Case statements are immutable. A complete ScenarioAssumptions set transforms latest-period statements, is canonically revalidated, and passes through the same ratio, DuPont, scoring and insight engines. Controls: {model.scenario.controls.join(", ")}. Presets: {model.scenario.presetNames.join(", ")}. Scenarios are sensitivities, not forecasts or probabilities.</p><p className="mt-3 text-caption text-neutral-400">EBIT-margin targets are operating sensitivities, not complete income-statement forecasts; taxes, financing schedules and accounting balancing are not invented.</p></MethodSection>
    <MethodSection id="limitations" icon={FileWarning} title="Assumptions, limitations and disclosure"><p>NovaTech Solutions and Atlas Manufacturing Group are fictional demonstration companies. Their values, scores and insights do not represent real companies. The application does not provide a credit rating, audit opinion, investment recommendation or substitute for professional judgement.</p><p className="mt-3 text-small font-semibold text-neutral-100">{model.disclaimer}</p><p className="mt-3 text-caption text-neutral-400">Technical traceability is available in the <Link className="text-primary underline" href="/engine-map">Engine Map <ExternalLink aria-hidden="true" className="inline h-3 w-3" /></Link>.</p></MethodSection>
  </div>;
}
function MethodSection({ children, icon: Icon, id, title }: { children: React.ReactNode; icon: typeof BookOpen; id: string; title: string }) { return <section className="scroll-mt-48 border border-border bg-surface p-4 md:p-5" id={id}><div className="flex gap-3"><Icon aria-hidden="true" className="mt-1 h-5 w-5 shrink-0 text-primary" /><div className="min-w-0"><h2 className="text-h4 font-semibold text-neutral-50">{title}</h2><div className="mt-3 text-small text-neutral-300">{children}</div></div></div></section>; }
